// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CGA_Server.Models
{
    public partial class Account
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateOnly? Creation { get; set; }
        public string Password { get; set; }
    }
}