// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CGA_Server.Models
{
    public partial class Country
    {
        public Country()
        {
            Location = new HashSet<Location>();
            Iid = new HashSet<Image>();
        }

        public int Cid { get; set; }
        public string Name { get; set; }
        public string NameNative { get; set; }
        public int? Population { get; set; }
        public int? Size { get; set; }
        public string Iso31661Alpha3Code { get; set; }
        public string Flag { get; set; }

        public virtual ICollection<Location> Location { get; set; }

        public virtual ICollection<Image> Iid { get; set; }
    }
}