// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CGA_Server.Models
{
    public partial class Image
    {
        public Image()
        {
            Cid = new HashSet<Country>();
            Lid = new HashSet<Location>();
        }

        public int Iid { get; set; }
        public string Name { get; set; }
        public string Image1 { get; set; }

        public virtual ICollection<Country> Cid { get; set; }
        public virtual ICollection<Location> Lid { get; set; }
    }
}