// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NpgsqlTypes;

namespace CGA_Server.Models
{
    public partial class Location
    {
        public Location()
        {
            Iid = new HashSet<Image>();
        }

        public int Lid { get; set; }
        public string Name { get; set; }
        public string NameNative { get; set; }
        public NpgsqlPoint? Coordinates { get; set; }
        public bool Iscapital { get; set; }
        public int Cid { get; set; }

        public virtual Country CidNavigation { get; set; }

        public virtual ICollection<Image> Iid { get; set; }
    }
}