// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CGA_Server.Models
{
    public partial class QuestionPresetBackup
    {
        public int Qid { get; set; }
        public string Name { get; set; }
        public string Preset { get; set; }
        public DateOnly Date { get; set; }
    }
}