// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CGA_Server.Models
{
    public partial class Score
    {
        public int Sid { get; set; }
        public int Score1 { get; set; }
        public DateOnly? Date { get; set; }
        public bool Ishighscore { get; set; }
        public int Pid { get; set; }

        public virtual Player PidNavigation { get; set; }
    }
}