// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CGA_Server.Models
{
    public partial class ScoresWithPlayers
    {
        public int? Sid { get; set; }
        public int? Score { get; set; }
        public DateTime? Date { get; set; }
        public string Name { get; set; }
    }
}